FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git ca-certificates tzdata curl bash

# Install Air for hot reload
RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app

# Copy dependencies
COPY shared/go.mod shared/go.sum ./shared/
COPY services/api-gateway/go.mod services/api-gateway/go.sum ./services/api-gateway/

WORKDIR /app/services/api-gateway

# Setup module replacement
RUN go mod edit -replace shared=../../shared
RUN go mod download

# Copy Air configuration
COPY services/api-gateway/.air.toml .air.toml

# Copy environment file
COPY services/api-gateway/.env .env

EXPOSE 8080 9090


# Add a development stage for Docker Compose build target
CMD ["air", "-c", ".air.toml"]
