CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE analytics.events (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    session_id          UUID REFERENCES auth.sessions(id) ON DELETE SET NULL,
    event_name          VARCHAR(255) NOT NULL,
    event_category      VARCHAR(100),
    event_action        VARCHAR(100),
    event_label         VARCHAR(255),
    event_value         DECIMAL(10,2),
    screen_name         VARCHAR(255),
    previous_screen     VARCHAR(255),
    flow_name           VARCHAR(100),
    device_id           VARCHAR(255),
    platform            VARCHAR(50),
    os_name             VARCHAR(100),
    os_version          VARCHAR(50),
    app_version         VARCHAR(50),
    app_build           VARCHAR(50),
    ip_address          INET,
    country             VARCHAR(100),
    region              VARCHAR(100),
    city                VARCHAR(100),
    timezone            VARCHAR(100),
    latitude            DECIMAL(10,8),
    longitude           DECIMAL(11,8),
    connection_type     VARCHAR(50),
    carrier             VARCHAR(100),
    event_duration_ms   INTEGER,
    load_time_ms        INTEGER,
    ttfb_ms             INTEGER,
    properties          JSONB DEFAULT '{}'::JSONB,
    utm_source          VARCHAR(255),
    utm_medium          VARCHAR(255),
    utm_campaign        VARCHAR(255),
    utm_term            VARCHAR(255),
    utm_content         VARCHAR(255),
    referrer            TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    event_timestamp     TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics.user_sessions (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id              UUID REFERENCES auth.sessions(id) ON DELETE CASCADE,
    session_start           TIMESTAMPTZ NOT NULL,
    session_end             TIMESTAMPTZ,
    session_duration_seconds INTEGER,
    page_views              INTEGER DEFAULT 0,
    screen_views            INTEGER DEFAULT 0,
    event_count             INTEGER DEFAULT 0,
    messages_sent           INTEGER DEFAULT 0,
    messages_received       INTEGER DEFAULT 0,
    device_id               VARCHAR(255),
    device_type             VARCHAR(50),
    platform                VARCHAR(50),
    app_version             VARCHAR(50),
    country                 VARCHAR(100),
    city                    VARCHAR(100),
    ip_address              INET,
    is_engaged              BOOLEAN DEFAULT FALSE,
    bounce                  BOOLEAN DEFAULT TRUE,
    traffic_source          VARCHAR(100),
    campaign                VARCHAR(255),
    created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics.daily_active_users (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date                    DATE NOT NULL,
    user_id                 UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    sessions_count          INTEGER DEFAULT 1,
    messages_sent           INTEGER DEFAULT 0,
    messages_received       INTEGER DEFAULT 0,
    time_spent_seconds      INTEGER DEFAULT 0,
    features_used           TEXT[],
    platforms_used          VARCHAR(50)[],
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, user_id)
);

CREATE TABLE analytics.user_cohorts (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    cohort_date             DATE NOT NULL,
    cohort_week             INTEGER,
    cohort_month            INTEGER,
    day_1_active            BOOLEAN DEFAULT FALSE,
    day_7_active            BOOLEAN DEFAULT FALSE,
    day_14_active           BOOLEAN DEFAULT FALSE,
    day_30_active           BOOLEAN DEFAULT FALSE,
    day_60_active           BOOLEAN DEFAULT FALSE,
    day_90_active           BOOLEAN DEFAULT FALSE,
    messages_sent_total     INTEGER DEFAULT 0,
    days_active_count       INTEGER DEFAULT 0,
    last_active_date        DATE,
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id)
);

CREATE TABLE analytics.funnels (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    session_id              UUID REFERENCES auth.sessions(id) ON DELETE SET NULL,
    funnel_name             VARCHAR(100) NOT NULL,
    step_name               VARCHAR(100) NOT NULL,
    step_order              INTEGER NOT NULL,
    entered_at              TIMESTAMPTZ DEFAULT NOW(),
    completed_at            TIMESTAMPTZ,
    time_in_step_seconds    INTEGER,
    is_completed            BOOLEAN DEFAULT FALSE,
    dropped_off             BOOLEAN DEFAULT FALSE,
    drop_off_reason         TEXT,
    properties              JSONB DEFAULT '{}'::JSONB,
    created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics.feature_usage (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    feature_name            VARCHAR(100) NOT NULL,
    feature_category        VARCHAR(100),
    usage_count             INTEGER DEFAULT 1,
    first_used_at           TIMESTAMPTZ DEFAULT NOW(),
    last_used_at            TIMESTAMPTZ DEFAULT NOW(),
    total_duration_seconds  INTEGER DEFAULT 0,
    engagement_score        DECIMAL(10,2),
    date                    DATE DEFAULT CURRENT_DATE,
    UNIQUE(user_id, feature_name, date)
);

CREATE TABLE analytics.ab_tests (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_name               VARCHAR(255) UNIQUE NOT NULL,
    test_description        TEXT,
    variants                JSONB NOT NULL,
    target_percentage       INTEGER DEFAULT 100,
    target_platforms        VARCHAR(50)[],
    target_countries        VARCHAR(5)[],
    target_user_segments    TEXT[],
    status                  VARCHAR(50) DEFAULT 'draft',
    starts_at               TIMESTAMPTZ,
    ends_at                 TIMESTAMPTZ,
    sample_size             INTEGER DEFAULT 0,
    confidence_level        DECIMAL(5,2),
    winning_variant         VARCHAR(100),
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW(),
    created_by_user_id      UUID REFERENCES auth.users(id)
);

CREATE TABLE analytics.ab_test_assignments (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id             UUID NOT NULL REFERENCES analytics.ab_tests(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    variant_name        VARCHAR(100) NOT NULL,
    variant_config      JSONB,
    converted           BOOLEAN DEFAULT FALSE,
    conversion_value    DECIMAL(10,2),
    converted_at        TIMESTAMPTZ,
    assigned_at         TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(test_id, user_id)
);

CREATE TABLE analytics.performance_metrics (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    metric_type         VARCHAR(100) NOT NULL,
    metric_name         VARCHAR(255) NOT NULL,
    metric_value        DECIMAL(15,4) NOT NULL,
    metric_unit         VARCHAR(50),
    service_name        VARCHAR(100),
    endpoint            VARCHAR(255),
    method              VARCHAR(20),
    status_code         INTEGER,
    duration_ms         INTEGER,
    memory_used_mb      INTEGER,
    cpu_percentage      DECIMAL(5,2),
    user_id             UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    session_id          UUID REFERENCES auth.sessions(id) ON DELETE SET NULL,
    ip_address          INET,
    is_error            BOOLEAN DEFAULT FALSE,
    error_message       TEXT,
    error_stack         TEXT,
    timestamp           TIMESTAMPTZ DEFAULT NOW(),
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics.error_logs (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    error_type              VARCHAR(100) NOT NULL,
    error_message           TEXT NOT NULL,
    error_code              VARCHAR(100),
    error_stack             TEXT,
    severity                VARCHAR(20) DEFAULT 'error',
    service_name            VARCHAR(100),
    function_name           VARCHAR(255),
    file_path               TEXT,
    line_number             INTEGER,
    user_id                 UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    session_id              UUID REFERENCES auth.sessions(id) ON DELETE SET NULL,
    device_id               VARCHAR(255),
    http_method             VARCHAR(20),
    endpoint                VARCHAR(255),
    request_id              VARCHAR(255),
    environment             VARCHAR(50),
    app_version             VARCHAR(50),
    platform                VARCHAR(50),
    occurrences             INTEGER DEFAULT 1,
    first_occurred_at       TIMESTAMPTZ DEFAULT NOW(),
    last_occurred_at        TIMESTAMPTZ DEFAULT NOW(),
    is_resolved             BOOLEAN DEFAULT FALSE,
    resolved_at             TIMESTAMPTZ,
    resolved_by_user_id     UUID REFERENCES auth.users(id),
    resolution_notes        TEXT,
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    metadata                JSONB DEFAULT '{}'::JSONB
);

CREATE TABLE analytics.daily_metrics (
    id                              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date                            DATE NOT NULL UNIQUE,
    dau                             INTEGER DEFAULT 0,
    new_users                       INTEGER DEFAULT 0,
    churned_users                   INTEGER DEFAULT 0,
    total_messages_sent             BIGINT DEFAULT 0,
    total_sessions                  BIGINT DEFAULT 0,
    avg_session_duration_seconds    INTEGER DEFAULT 0,
    avg_messages_per_user           DECIMAL(10,2) DEFAULT 0.00,
    images_uploaded                 INTEGER DEFAULT 0,
    videos_uploaded                 INTEGER DEFAULT 0,
    voice_messages_sent             INTEGER DEFAULT 0,
    new_conversations               INTEGER DEFAULT 0,
    new_groups_created              INTEGER DEFAULT 0,
    new_friendships                 INTEGER DEFAULT 0,
    voice_calls_total               INTEGER DEFAULT 0,
    video_calls_total               INTEGER DEFAULT 0,
    total_call_duration_minutes     BIGINT DEFAULT 0,
    revenue_total                   DECIMAL(10,2) DEFAULT 0.00,
    new_subscriptions               INTEGER DEFAULT 0,
    cancelled_subscriptions         INTEGER DEFAULT 0,
    avg_api_latency_ms              INTEGER,
    error_count                     INTEGER DEFAULT 0,
    uptime_percentage               DECIMAL(5,2) DEFAULT 100.00,
    created_at                      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics.user_segments (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    segment_name        VARCHAR(100) NOT NULL,
    segment_category    VARCHAR(100),
    criteria_met        JSONB,
    confidence_score    DECIMAL(5,2),
    assigned_at         TIMESTAMPTZ DEFAULT NOW(),
    expires_at          TIMESTAMPTZ,
    is_active           BOOLEAN DEFAULT TRUE,
    UNIQUE(user_id, segment_name)
);

CREATE TABLE analytics.revenue_events (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    transaction_type        VARCHAR(100) NOT NULL,
    product_id              VARCHAR(255),
    product_name            VARCHAR(255),
    product_category        VARCHAR(100),
    amount                  DECIMAL(10,2) NOT NULL,
    currency                VARCHAR(10) DEFAULT 'USD',
    amount_usd              DECIMAL(10,2),
    payment_method          VARCHAR(100),
    payment_provider        VARCHAR(100),
    transaction_id          VARCHAR(255) UNIQUE,
    status                  VARCHAR(50) DEFAULT 'completed',
    refunded_at             TIMESTAMPTZ,
    refund_amount           DECIMAL(10,2),
    refund_reason           TEXT,
    campaign_source         VARCHAR(255),
    is_subscription         BOOLEAN DEFAULT FALSE,
    subscription_period     VARCHAR(50),
    is_trial                BOOLEAN DEFAULT FALSE,
    is_renewal              BOOLEAN DEFAULT FALSE,
    transaction_date        TIMESTAMPTZ DEFAULT NOW(),
    created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics.user_ltv (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                     UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    total_revenue               DECIMAL(10,2) DEFAULT 0.00,
    total_transactions          INTEGER DEFAULT 0,
    average_transaction_value   DECIMAL(10,2) DEFAULT 0.00,
    days_active                 INTEGER DEFAULT 0,
    messages_sent_total         INTEGER DEFAULT 0,
    messages_received_total     INTEGER DEFAULT 0,
    predicted_ltv_30d           DECIMAL(10,2),
    predicted_ltv_90d           DECIMAL(10,2),
    predicted_ltv_365d          DECIMAL(10,2),
    user_segment                VARCHAR(100),
    churn_risk_score            DECIMAL(5,2),
    last_calculated_at          TIMESTAMPTZ DEFAULT NOW(),
    created_at                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics.churn_predictions (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                     UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    churn_probability           DECIMAL(5,2) NOT NULL,
    churn_risk_level            VARCHAR(20),
    contributing_factors        JSONB,
    predicted_churn_date        DATE,
    days_until_churn            INTEGER,
    intervention_recommended    VARCHAR(255),
    intervention_sent           BOOLEAN DEFAULT FALSE,
    intervention_sent_at        TIMESTAMPTZ,
    actually_churned            BOOLEAN,
    churn_date                  DATE,
    prediction_date             DATE DEFAULT CURRENT_DATE,
    model_version               VARCHAR(50),
    confidence_score            DECIMAL(5,2),
    created_at                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE analytics.api_usage (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    endpoint                VARCHAR(255) NOT NULL,
    method                  VARCHAR(20) NOT NULL,
    service_name            VARCHAR(100),
    user_id                 UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    api_key_id              UUID REFERENCES auth.api_keys(id) ON DELETE SET NULL,
    request_size_bytes      INTEGER,
    query_params            JSONB,
    status_code             INTEGER NOT NULL,
    response_size_bytes     INTEGER,
    response_time_ms        INTEGER,
    db_query_time_ms        INTEGER,
    cache_hit               BOOLEAN DEFAULT FALSE,
    ip_address              INET,
    country                 VARCHAR(100),
    is_error                BOOLEAN DEFAULT FALSE,
    error_code              VARCHAR(100),
    error_message           TEXT,
    timestamp               TIMESTAMPTZ DEFAULT NOW(),
    created_at              TIMESTAMPTZ DEFAULT NOW()
);
