CREATE SCHEMA IF NOT EXISTS location;

CREATE TABLE location.ip_addresses (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ip_address          INET UNIQUE NOT NULL,
    ip_version          INTEGER,
    country_code        VARCHAR(5),
    country_name        VARCHAR(100),
    region_code         VARCHAR(10),
    region_name         VARCHAR(100),
    city                VARCHAR(100),
    postal_code         VARCHAR(20),
    latitude            DECIMAL(10,8),
    longitude           DECIMAL(11,8),
    metro_code          VARCHAR(20),
    timezone            VARCHAR(100),
    isp                 VARCHAR(255),
    organization        VARCHAR(255),
    asn                 VARCHAR(50),
    as_organization     VARCHAR(255),
    connection_type     VARCHAR(50),
    user_type           VARCHAR(50),
    is_proxy            BOOLEAN DEFAULT FALSE,
    is_vpn              BOOLEAN DEFAULT FALSE,
    is_tor              BOOLEAN DEFAULT FALSE,
    is_hosting          BOOLEAN DEFAULT FALSE,
    is_anonymous        BOOLEAN DEFAULT FALSE,
    threat_level        VARCHAR(20),
    risk_score          INTEGER,
    is_bogon            BOOLEAN DEFAULT FALSE,
    first_seen_at       TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at        TIMESTAMPTZ DEFAULT NOW(),
    lookup_count        INTEGER DEFAULT 1,
    user_count          INTEGER DEFAULT 0,
    lookup_provider     VARCHAR(50),
    last_updated_at     TIMESTAMPTZ DEFAULT NOW(),
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    metadata            JSONB DEFAULT '{}'::JSONB
);

CREATE TABLE location.user_locations (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id                  UUID REFERENCES auth.sessions(id) ON DELETE SET NULL,
    ip_address_id               UUID REFERENCES location.ip_addresses(id),
    ip_address                  INET NOT NULL,
    latitude                    DECIMAL(10,8),
    longitude                   DECIMAL(11,8),
    accuracy_meters             INTEGER,
    altitude                    DECIMAL(10,2),
    country                     VARCHAR(100),
    region                      VARCHAR(100),
    city                        VARCHAR(100),
    postal_code                 VARCHAR(20),
    address                     TEXT,
    location_type               VARCHAR(50),
    location_source             VARCHAR(50),
    is_new_location             BOOLEAN DEFAULT FALSE,
    is_new_country              BOOLEAN DEFAULT FALSE,
    is_new_city                 BOOLEAN DEFAULT FALSE,
    distance_from_previous_km   DECIMAL(10,2),
    timezone                    VARCHAR(100),
    timezone_offset             INTEGER,
    device_id                   VARCHAR(255),
    captured_at                 TIMESTAMPTZ DEFAULT NOW(),
    created_at                  TIMESTAMPTZ DEFAULT NOW(),
    metadata                    JSONB DEFAULT '{}'::JSONB
);

CREATE TABLE location.location_shares (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    shared_with_user_id         UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    shared_with_conversation_id UUID REFERENCES messages.conversations(id) ON DELETE CASCADE,
    latitude                    DECIMAL(10,8) NOT NULL,
    longitude                   DECIMAL(11,8) NOT NULL,
    accuracy_meters             INTEGER,
    altitude                    DECIMAL(10,2),
    heading                     DECIMAL(5,2),
    speed_mps                   DECIMAL(10,2),
    share_type                  VARCHAR(50) DEFAULT 'temporary',
    duration_minutes            INTEGER,
    expires_at                  TIMESTAMPTZ,
    is_active                   BOOLEAN DEFAULT TRUE,
    is_live                     BOOLEAN DEFAULT TRUE,
    update_interval_seconds     INTEGER DEFAULT 30,
    show_exact_location         BOOLEAN DEFAULT TRUE,
    show_address                BOOLEAN DEFAULT FALSE,
    started_at                  TIMESTAMPTZ DEFAULT NOW(),
    stopped_at                  TIMESTAMPTZ,
    last_updated_at             TIMESTAMPTZ DEFAULT NOW(),
    created_at                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE location.location_updates (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    location_share_id   UUID NOT NULL REFERENCES location.location_shares(id) ON DELETE CASCADE,
    latitude            DECIMAL(10,8) NOT NULL,
    longitude           DECIMAL(11,8) NOT NULL,
    accuracy_meters     INTEGER,
    altitude            DECIMAL(10,2),
    heading             DECIMAL(5,2),
    speed_mps           DECIMAL(10,2),
    battery_level       INTEGER,
    is_charging         BOOLEAN,
    timestamp           TIMESTAMPTZ DEFAULT NOW(),
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE location.places (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    place_name          VARCHAR(255) NOT NULL,
    place_type          VARCHAR(100),
    place_category      VARCHAR(100),
    latitude            DECIMAL(10,8) NOT NULL,
    longitude           DECIMAL(11,8) NOT NULL,
    address             TEXT,
    city                VARCHAR(100),
    region              VARCHAR(100),
    country             VARCHAR(100),
    postal_code         VARCHAR(20),
    phone_number        VARCHAR(20),
    website_url         TEXT,
    google_place_id     VARCHAR(255) UNIQUE,
    foursquare_id       VARCHAR(255),
    rating              DECIMAL(3,2),
    review_count        INTEGER DEFAULT 0,
    price_level         INTEGER,
    check_in_count      INTEGER DEFAULT 0,
    share_count         INTEGER DEFAULT 0,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE location.check_ins (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    place_id        UUID REFERENCES location.places(id) ON DELETE SET NULL,
    latitude        DECIMAL(10,8),
    longitude       DECIMAL(11,8),
    place_name      VARCHAR(255),
    caption         TEXT,
    photo_url       TEXT,
    visibility      VARCHAR(50) DEFAULT 'friends',
    like_count      INTEGER DEFAULT 0,
    comment_count   INTEGER DEFAULT 0,
    checked_in_at   TIMESTAMPTZ DEFAULT NOW(),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE location.geofences (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    fence_name              VARCHAR(255) NOT NULL,
    fence_type              VARCHAR(50),
    center_latitude         DECIMAL(10,8),
    center_longitude        DECIMAL(11,8),
    radius_meters           INTEGER,
    polygon_coordinates     JSONB,
    trigger_on_enter        BOOLEAN DEFAULT TRUE,
    trigger_on_exit         BOOLEAN DEFAULT FALSE,
    trigger_on_dwell        BOOLEAN DEFAULT FALSE,
    dwell_time_seconds      INTEGER,
    action_type             VARCHAR(100),
    action_config           JSONB,
    is_active               BOOLEAN DEFAULT TRUE,
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE location.geofence_events (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    geofence_id         UUID NOT NULL REFERENCES location.geofences(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    event_type          VARCHAR(50) NOT NULL,
    latitude            DECIMAL(10,8),
    longitude           DECIMAL(11,8),
    action_executed     BOOLEAN DEFAULT FALSE,
    action_result       JSONB,
    occurred_at         TIMESTAMPTZ DEFAULT NOW(),
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE location.ip_blacklist (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ip_address              INET NOT NULL,
    ip_range                CIDR,
    blacklist_reason        VARCHAR(255) NOT NULL,
    blacklist_type          VARCHAR(50),
    severity                VARCHAR(20) DEFAULT 'medium',
    incident_count          INTEGER DEFAULT 1,
    evidence_urls           TEXT[],
    notes                   TEXT,
    is_active               BOOLEAN DEFAULT TRUE,
    blacklisted_by_user_id  UUID REFERENCES auth.users(id),
    source                  VARCHAR(100),
    blacklisted_at          TIMESTAMPTZ DEFAULT NOW(),
    expires_at              TIMESTAMPTZ,
    removed_at              TIMESTAMPTZ,
    created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE location.vpn_detection_log (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id          UUID REFERENCES auth.sessions(id) ON DELETE SET NULL,
    ip_address          INET NOT NULL,
    is_vpn              BOOLEAN DEFAULT FALSE,
    is_proxy            BOOLEAN DEFAULT FALSE,
    is_tor              BOOLEAN DEFAULT FALSE,
    is_hosting          BOOLEAN DEFAULT FALSE,
    vpn_provider        VARCHAR(255),
    proxy_type          VARCHAR(50),
    confidence_score    DECIMAL(5,2),
    action_taken        VARCHAR(100),
    detected_at         TIMESTAMPTZ DEFAULT NOW(),
    created_at          TIMESTAMPTZ DEFAULT NOW()
);
