# =============================================================================
# HELP SYSTEM
# =============================================================================

.PHONY: help

help:
	@echo ""
	@echo "$(BOLD)$(BRIGHT_CYAN)ECHO BACKEND$(NC) $(DIM)- Microservices Management$(NC)"
	@echo ""
	@echo "$(YELLOW)Environment:$(NC) $(BOLD)$(ENV_NAME)$(NC)"
	@echo ""
	@echo "$(UNDERLINE)$(BOLD)Main Commands$(NC)"
	@echo "  $(BRIGHT_GREEN)make up$(NC)                  $(ARROW) Start all services"
	@echo "  $(BRIGHT_GREEN)make down$(NC)                $(ARROW) Stop all services"
	@echo "  $(BRIGHT_GREEN)make restart$(NC)             $(ARROW) Restart all services"
	@echo "  $(BRIGHT_GREEN)make build$(NC)               $(ARROW) Build all service images"
	@echo "  $(BRIGHT_GREEN)make rerun$(NC)               $(ARROW) Rebuild and restart all services"
	@echo "  $(BRIGHT_GREEN)make logs$(NC)                $(ARROW) View logs from all services"
	@echo "  $(BRIGHT_GREEN)make status$(NC)              $(ARROW) Show status of all services"
	@echo "  $(BRIGHT_GREEN)make ps$(NC)                  $(ARROW) Show running containers"
	@echo "  $(BRIGHT_GREEN)make clean$(NC)               $(ARROW) Stop and remove everything $(BRIGHT_RED)(including volumes)$(NC)"
	@echo ""
	@echo "$(UNDERLINE)$(BOLD)Individual Services$(NC)"
	@echo "  $(BLUE)Gateway:$(NC)      make gateway-{up,down,logs,restart,build,rerun}"
	@echo "  $(MAGENTA)Auth:$(NC)         make auth-{up,down,logs,restart,build,rerun}"
	@echo "  $(GREEN)User:$(NC)         make user-{up,down,logs,restart,build,rerun}"
	@echo "  $(CYAN)Message:$(NC)      make message-{up,down,logs,restart,build,rerun}"
	@echo "  $(YELLOW)Location:$(NC)     make location-{up,down,logs,restart,build,rerun}"
	@echo "  $(MAGENTA)Media:$(NC)        make media-{up,down,logs,restart,build,rerun}"
	@echo "  $(BLUE)Presence:$(NC)     make presence-{up,down,logs,restart,build,rerun}"
	@echo ""
	@echo "$(UNDERLINE)$(BOLD)Infrastructure$(NC)"
	@echo "  $(YELLOW)Kafka:$(NC)        make kafka-{up,down,logs,restart,topics,create-topics}"
	@echo "  $(GREEN)Database:$(NC)     make db-{up,init,seed,connect,reset,migrate,clean}"
	@echo "  $(RED)Redis:$(NC)        make redis-{connect,flush}"
	@echo ""
	@echo "$(UNDERLINE)$(BOLD)Development$(NC)"
	@echo "  $(BRIGHT_CYAN)make setup$(NC)               $(ARROW) Initial project setup"
	@echo "  $(BRIGHT_CYAN)make dev$(NC)                 $(ARROW) Start in development mode with logs"
	@echo "  $(BRIGHT_CYAN)make health$(NC)              $(ARROW) Check health of all services"
	@echo "  $(BRIGHT_CYAN)make test$(NC)                $(ARROW) Run all tests"
	@echo "  $(BRIGHT_CYAN)make test-auth$(NC)           $(ARROW) Test auth endpoints"
	@echo "  $(BRIGHT_CYAN)make verify-security$(NC)     $(ARROW) Verify security configuration"
	@echo ""
	@echo "$(UNDERLINE)$(BOLD)Utilities$(NC)"
	@echo "  $(CYAN)make generate-routes$(NC)     $(ARROW) Generate routes from registry"
	@echo "  $(CYAN)make update-gateway-routes$(NC) $(ARROW) Update gateway configuration"
	@echo "  $(CYAN)make format-code$(NC)         $(ARROW) Format all Go code"
	@echo ""
	@echo "$(DIM)For more details on a specific service, run: make <service>-help$(NC)"
	@echo ""